"""
Network Inventory Use Case - Demo Data

Sample network inventory for a home office / small business setup.
"""

from datetime import date, datetime

# Physical Locations (hierarchical)
LOCATIONS = [
    {
        "location_code": "HOME",
        "location_type": "building",
        "name": "Home Office",
        "address": "123 Main Street",
    },
    {
        "location_code": "HOME-GF",
        "location_type": "floor",
        "name": "Ground Floor",
        "parent_location": "HOME",
        "floor_number": 0,
    },
    {
        "location_code": "HOME-1F",
        "location_type": "floor",
        "name": "First Floor",
        "parent_location": "HOME",
        "floor_number": 1,
    },
    {
        "location_code": "CLOSET-A",
        "location_type": "room",
        "name": "Network Closet",
        "parent_location": "HOME-GF",
        "notes": "Under stairs, contains main network equipment",
    },
    {
        "location_code": "OFFICE",
        "location_type": "room",
        "name": "Home Office",
        "parent_location": "HOME-1F",
    },
    {
        "location_code": "RACK-A",
        "location_type": "rack",
        "name": "Main Rack",
        "parent_location": "CLOSET-A",
        "notes": "12U wall-mount rack",
    },
]

# VLANs
VLANS = [
    {
        "vlan_id": 1,
        "name": "Default",
        "purpose": "management",
        "subnet": "192.168.1.0/24",
        "gateway": "192.168.1.1",
        "dhcp_enabled": True,
        "dhcp_start": "192.168.1.100",
        "dhcp_end": "192.168.1.199",
        "dns_servers": "192.168.1.1",
        "description": "Default management VLAN",
    },
    {
        "vlan_id": 10,
        "name": "Users",
        "purpose": "user_data",
        "subnet": "192.168.10.0/24",
        "gateway": "192.168.10.1",
        "dhcp_enabled": True,
        "dhcp_start": "192.168.10.100",
        "dhcp_end": "192.168.10.199",
        "dns_servers": "192.168.10.1,8.8.8.8",
        "description": "User workstations and laptops",
    },
    {
        "vlan_id": 20,
        "name": "IoT",
        "purpose": "iot",
        "subnet": "192.168.20.0/24",
        "gateway": "192.168.20.1",
        "dhcp_enabled": True,
        "dhcp_start": "192.168.20.100",
        "dhcp_end": "192.168.20.199",
        "dns_servers": "192.168.20.1",
        "description": "IoT devices - isolated from main network",
    },
    {
        "vlan_id": 30,
        "name": "Cameras",
        "purpose": "security_cameras",
        "subnet": "192.168.30.0/24",
        "gateway": "192.168.30.1",
        "dhcp_enabled": True,
        "dhcp_start": "192.168.30.100",
        "dhcp_end": "192.168.30.199",
        "dns_servers": "192.168.30.1",
        "description": "IP cameras - no internet access",
    },
    {
        "vlan_id": 99,
        "name": "Guest",
        "purpose": "guest",
        "subnet": "192.168.99.0/24",
        "gateway": "192.168.99.1",
        "dhcp_enabled": True,
        "dhcp_start": "192.168.99.100",
        "dhcp_end": "192.168.99.199",
        "dns_servers": "8.8.8.8,8.8.4.4",
        "description": "Guest WiFi - internet only",
    },
]

# Network Devices
DEVICES = [
    # Router/Firewall
    {
        "template": "NET_DEVICE",
        "hostname": "gw-main",
        "mac_address": "00:1A:2B:3C:4D:01",
        "device_type": "router",
        "manufacturer": "ubiquiti",
        "model": "EdgeRouter 4",
        "serial_number": "ER4-123456789",
        "firmware_version": "2.0.9-hotfix.7",
        "management_ip": "192.168.1.1",
        "location_code": "RACK-A",
        "rack_unit": 1,
        "rack_height": 1,
        "status": "active",
        "purchase_date": "2022-03-15",
        "warranty_expiry": "2025-03-15",
        "purchase_price": 349.00,
        "power_watts": 12,
        "notes": "Main gateway, handles inter-VLAN routing",
    },
    # Main Managed Switch (PoE)
    {
        "template": "NET_SWITCH",
        "hostname": "sw-main",
        "mac_address": "00:1A:2B:3C:4D:10",
        "device_type": "switch",
        "manufacturer": "ubiquiti",
        "model": "UniFi Switch 24 PoE",
        "serial_number": "US24P-987654321",
        "firmware_version": "6.5.59",
        "management_ip": "192.168.1.10",
        "location_code": "RACK-A",
        "rack_unit": 2,
        "rack_height": 1,
        "status": "active",
        "purchase_date": "2022-03-15",
        "warranty_expiry": "2025-03-15",
        "purchase_price": 499.00,
        "power_watts": 30,
        "is_managed": True,
        "layer": 2,
        "total_ports": 24,
        "poe_budget_watts": 250,
        "poe_consumed_watts": 45,
        "supports_stacking": False,
        "management_vlan": 1,
        "spanning_tree_mode": "RSTP",
    },
    # Secondary Unmanaged Switch
    {
        "template": "NET_SWITCH",
        "hostname": "sw-office",
        "mac_address": "00:1A:2B:3C:4D:20",
        "device_type": "switch",
        "manufacturer": "netgear",
        "model": "GS108",
        "serial_number": "GS108-ABC123",
        "firmware_version": "N/A",
        "location_code": "OFFICE",
        "status": "active",
        "purchase_date": "2021-06-01",
        "warranty_expiry": "2024-06-01",
        "purchase_price": 39.99,
        "power_watts": 5,
        "is_managed": False,
        "layer": 2,
        "total_ports": 8,
        "poe_budget_watts": 0,
        "notes": "Simple unmanaged switch under desk",
    },
    # Access Point
    {
        "template": "NET_DEVICE",
        "hostname": "ap-living",
        "mac_address": "00:1A:2B:3C:4D:30",
        "device_type": "access_point",
        "manufacturer": "ubiquiti",
        "model": "UniFi U6-Lite",
        "serial_number": "U6L-WIFI-001",
        "firmware_version": "6.5.62",
        "management_ip": "192.168.1.30",
        "location_code": "HOME-GF",
        "status": "active",
        "purchase_date": "2023-01-10",
        "warranty_expiry": "2026-01-10",
        "purchase_price": 99.00,
        "power_watts": 12,
        "notes": "Ceiling mounted, PoE powered",
    },
    # NAS
    {
        "template": "NET_DEVICE",
        "hostname": "nas-main",
        "mac_address": "00:1A:2B:3C:4D:40",
        "device_type": "nas",
        "manufacturer": "synology",
        "model": "DS920+",
        "serial_number": "SYN-DS920-123",
        "firmware_version": "DSM 7.2-64570",
        "management_ip": "192.168.1.40",
        "location_code": "RACK-A",
        "rack_unit": 4,
        "rack_height": 2,
        "status": "active",
        "purchase_date": "2021-11-20",
        "warranty_expiry": "2024-11-20",
        "purchase_price": 549.00,
        "power_watts": 45,
        "notes": "4-bay NAS, 32TB usable",
    },
    # Workstation
    {
        "template": "NET_DEVICE",
        "hostname": "ws-peter",
        "mac_address": "00:1A:2B:3C:4D:50",
        "device_type": "workstation",
        "manufacturer": "apple",
        "model": "Mac Mini M2",
        "serial_number": "C02ABC123",
        "firmware_version": "macOS 14.2",
        "management_ip": "192.168.10.50",
        "location_code": "OFFICE",
        "status": "active",
        "purchase_date": "2023-06-15",
        "warranty_expiry": "2024-06-15",
        "purchase_price": 599.00,
        "power_watts": 22,
    },
    # Raspberry Pi (this one!)
    {
        "template": "NET_DEVICE",
        "hostname": "wip-dev-pi",
        "mac_address": "DC:A6:32:AA:BB:CC",
        "device_type": "server",
        "manufacturer": "raspberry_pi",
        "model": "Raspberry Pi 5 8GB",
        "serial_number": "RPI5-WIP-001",
        "firmware_version": "Raspbian 12",
        "management_ip": "192.168.1.17",
        "location_code": "RACK-A",
        "rack_unit": 3,
        "rack_height": 1,
        "status": "active",
        "purchase_date": "2024-01-01",
        "warranty_expiry": "2025-01-01",
        "purchase_price": 80.00,
        "power_watts": 8,
        "notes": "Running WIP development environment",
    },
    # IP Camera
    {
        "template": "NET_DEVICE",
        "hostname": "cam-front",
        "mac_address": "00:1A:2B:3C:4D:60",
        "device_type": "ip_camera",
        "manufacturer": "ubiquiti",
        "model": "G4 Bullet",
        "serial_number": "UVC-G4B-001",
        "firmware_version": "4.63.22",
        "management_ip": "192.168.30.60",
        "location_code": "HOME-GF",
        "status": "active",
        "purchase_date": "2023-04-01",
        "warranty_expiry": "2025-04-01",
        "purchase_price": 199.00,
        "power_watts": 8,
        "notes": "Front door camera, PoE powered",
    },
    # IoT Device
    {
        "template": "NET_DEVICE",
        "hostname": "thermostat",
        "mac_address": "00:1A:2B:3C:4D:70",
        "device_type": "iot_sensor",
        "manufacturer": "other",
        "model": "Ecobee Smart Thermostat",
        "serial_number": "ECO-THERM-001",
        "management_ip": "192.168.20.70",
        "location_code": "HOME-GF",
        "status": "active",
        "purchase_date": "2022-09-01",
        "power_watts": 3,
    },
]

# Switch Ports (main switch)
SWITCH_PORTS = [
    # Uplink to router
    {
        "switch_mac": "00:1A:2B:3C:4D:10",
        "port_id": "1",
        "port_label": "Uplink",
        "speed_capability": "1g",
        "current_speed": "1g",
        "poe_capability": "none",
        "admin_status": "up",
        "link_status": "up",
        "vlan_mode": "trunk",
        "trunk_vlans": "1,10,20,30,99",
        "native_vlan": 1,
        "connected_mac": "00:1A:2B:3C:4D:01",
        "connected_hostname": "gw-main",
        "description": "Uplink to gateway",
    },
    # Access Point
    {
        "switch_mac": "00:1A:2B:3C:4D:10",
        "port_id": "2",
        "port_label": "AP-Living",
        "speed_capability": "1g",
        "current_speed": "1g",
        "poe_capability": "at_30w",
        "poe_allocated_watts": 15,
        "poe_drawn_watts": 12,
        "admin_status": "up",
        "link_status": "up",
        "vlan_mode": "trunk",
        "trunk_vlans": "10,20,99",
        "native_vlan": 1,
        "connected_mac": "00:1A:2B:3C:4D:30",
        "connected_hostname": "ap-living",
        "description": "UniFi AP - Living Room",
    },
    # NAS
    {
        "switch_mac": "00:1A:2B:3C:4D:10",
        "port_id": "3",
        "port_label": "NAS",
        "speed_capability": "1g",
        "current_speed": "1g",
        "poe_capability": "at_30w",
        "admin_status": "up",
        "link_status": "up",
        "vlan_mode": "access",
        "access_vlan": 1,
        "connected_mac": "00:1A:2B:3C:4D:40",
        "connected_hostname": "nas-main",
        "description": "Synology NAS",
    },
    # Raspberry Pi
    {
        "switch_mac": "00:1A:2B:3C:4D:10",
        "port_id": "4",
        "port_label": "Pi-WIP",
        "speed_capability": "1g",
        "current_speed": "1g",
        "poe_capability": "at_30w",
        "admin_status": "up",
        "link_status": "up",
        "vlan_mode": "access",
        "access_vlan": 1,
        "connected_mac": "DC:A6:32:AA:BB:CC",
        "connected_hostname": "wip-dev-pi",
        "description": "WIP Development Server",
    },
    # IP Camera
    {
        "switch_mac": "00:1A:2B:3C:4D:10",
        "port_id": "5",
        "port_label": "Cam-Front",
        "speed_capability": "1g",
        "current_speed": "100m",
        "poe_capability": "at_30w",
        "poe_allocated_watts": 12,
        "poe_drawn_watts": 8,
        "admin_status": "up",
        "link_status": "up",
        "vlan_mode": "access",
        "access_vlan": 30,
        "connected_mac": "00:1A:2B:3C:4D:60",
        "connected_hostname": "cam-front",
        "description": "Front door camera",
    },
    # To office switch
    {
        "switch_mac": "00:1A:2B:3C:4D:10",
        "port_id": "10",
        "port_label": "Office-SW",
        "speed_capability": "1g",
        "current_speed": "1g",
        "poe_capability": "at_30w",
        "admin_status": "up",
        "link_status": "up",
        "vlan_mode": "access",
        "access_vlan": 10,
        "connected_mac": "00:1A:2B:3C:4D:20",
        "connected_hostname": "sw-office",
        "description": "To office switch via patch panel",
    },
    # Empty ports
    {
        "switch_mac": "00:1A:2B:3C:4D:10",
        "port_id": "20",
        "speed_capability": "1g",
        "poe_capability": "at_30w",
        "admin_status": "up",
        "link_status": "down",
        "vlan_mode": "access",
        "access_vlan": 10,
        "description": "Available",
    },
    {
        "switch_mac": "00:1A:2B:3C:4D:10",
        "port_id": "21",
        "speed_capability": "1g",
        "poe_capability": "at_30w",
        "admin_status": "up",
        "link_status": "down",
        "vlan_mode": "access",
        "access_vlan": 10,
        "description": "Available",
    },
    # SFP ports
    {
        "switch_mac": "00:1A:2B:3C:4D:10",
        "port_id": "SFP1",
        "speed_capability": "1g",
        "poe_capability": "none",
        "admin_status": "up",
        "link_status": "down",
        "vlan_mode": "trunk",
        "description": "SFP uplink - unused",
    },
]

# Patch Panel
PATCH_PANELS = [
    {
        "panel_id": "PP-A",
        "name": "Patch Panel A",
        "location_code": "RACK-A",
        "rack_unit": 5,
        "rack_height": 1,
        "total_ports": 24,
        "port_type": "cat6a",
        "notes": "Home runs from all rooms",
    },
]

# Patch Panel Ports (subset for demo)
PATCH_PORTS = [
    {
        "panel_id": "PP-A",
        "port_number": 1,
        "port_label": "Office-1",
        "front_type": "wallplate",
        "front_reference": "OFFICE-WP1",
        "back_type": "switch_port",
        "back_switch_mac": "00:1A:2B:3C:4D:10",
        "back_port_id": "10",
        "cable_type": "cat6a",
        "tested_date": "2022-03-20",
        "test_result": "pass",
    },
    {
        "panel_id": "PP-A",
        "port_number": 2,
        "port_label": "Office-2",
        "front_type": "wallplate",
        "front_reference": "OFFICE-WP2",
        "back_type": "switch_port",
        "back_switch_mac": "00:1A:2B:3C:4D:10",
        "back_port_id": "20",
        "cable_type": "cat6a",
        "tested_date": "2022-03-20",
        "test_result": "pass",
    },
    {
        "panel_id": "PP-A",
        "port_number": 3,
        "port_label": "Living-1",
        "front_type": "device",
        "front_reference": "00:1A:2B:3C:4D:30",  # AP MAC
        "back_type": "switch_port",
        "back_switch_mac": "00:1A:2B:3C:4D:10",
        "back_port_id": "2",
        "cable_type": "cat6",
        "tested_date": "2023-01-15",
        "test_result": "pass",
    },
]

# Cables
CABLES = [
    {
        "cable_id": "CAB-001",
        "cable_type": "cat6a",
        "cable_color": "blue",
        "length_meters": 1.0,
        "endpoint_a_type": "switch_port",
        "endpoint_a_device_mac": "00:1A:2B:3C:4D:10",
        "endpoint_a_port_id": "1",
        "endpoint_b_type": "device",
        "endpoint_b_device_mac": "00:1A:2B:3C:4D:01",
        "install_date": "2022-03-15",
        "test_result": "pass",
        "notes": "Switch to router uplink",
    },
    {
        "cable_id": "CAB-002",
        "cable_type": "cat6",
        "cable_color": "yellow",
        "length_meters": 15.0,
        "endpoint_a_type": "patch_port",
        "endpoint_a_panel_id": "PP-A",
        "endpoint_a_port_number": 3,
        "endpoint_b_type": "device",
        "endpoint_b_device_mac": "00:1A:2B:3C:4D:30",
        "install_date": "2023-01-10",
        "test_result": "pass",
        "notes": "Run to living room AP",
    },
    {
        "cable_id": "CAB-003",
        "cable_type": "cat6a",
        "cable_color": "blue",
        "length_meters": 20.0,
        "endpoint_a_type": "patch_port",
        "endpoint_a_panel_id": "PP-A",
        "endpoint_a_port_number": 1,
        "endpoint_b_type": "wallplate",
        "endpoint_b_location": "OFFICE-WP1",
        "install_date": "2022-03-15",
        "test_result": "pass",
        "notes": "Home run to office wall plate 1",
    },
    {
        "cable_id": "CAB-004",
        "cable_type": "cat6",
        "cable_color": "gray",
        "length_meters": 2.0,
        "endpoint_a_type": "switch_port",
        "endpoint_a_device_mac": "00:1A:2B:3C:4D:10",
        "endpoint_a_port_id": "3",
        "endpoint_b_type": "device",
        "endpoint_b_device_mac": "00:1A:2B:3C:4D:40",
        "install_date": "2021-11-20",
        "test_result": "pass",
        "notes": "Direct to NAS",
    },
    {
        "cable_id": "CAB-005",
        "cable_type": "cat6",
        "cable_color": "black",
        "length_meters": 0.5,
        "endpoint_a_type": "switch_port",
        "endpoint_a_device_mac": "00:1A:2B:3C:4D:10",
        "endpoint_a_port_id": "4",
        "endpoint_b_type": "device",
        "endpoint_b_device_mac": "DC:A6:32:AA:BB:CC",
        "install_date": "2024-01-01",
        "test_result": "pass",
        "notes": "Raspberry Pi WIP server",
    },
]

# IP Assignments
IP_ASSIGNMENTS = [
    {"ip_address": "192.168.1.1", "mac_address": "00:1A:2B:3C:4D:01", "hostname": "gw-main", "vlan_id": 1, "assignment_type": "static", "dns_name": "gw-main.local"},
    {"ip_address": "192.168.1.10", "mac_address": "00:1A:2B:3C:4D:10", "hostname": "sw-main", "vlan_id": 1, "assignment_type": "static", "dns_name": "sw-main.local"},
    {"ip_address": "192.168.1.17", "mac_address": "DC:A6:32:AA:BB:CC", "hostname": "wip-dev-pi", "vlan_id": 1, "assignment_type": "static", "dns_name": "wip-dev-pi.local"},
    {"ip_address": "192.168.1.30", "mac_address": "00:1A:2B:3C:4D:30", "hostname": "ap-living", "vlan_id": 1, "assignment_type": "dhcp_reservation"},
    {"ip_address": "192.168.1.40", "mac_address": "00:1A:2B:3C:4D:40", "hostname": "nas-main", "vlan_id": 1, "assignment_type": "static", "dns_name": "nas-main.local"},
    {"ip_address": "192.168.10.50", "mac_address": "00:1A:2B:3C:4D:50", "hostname": "ws-peter", "vlan_id": 10, "assignment_type": "dhcp_reservation"},
    {"ip_address": "192.168.20.70", "mac_address": "00:1A:2B:3C:4D:70", "hostname": "thermostat", "vlan_id": 20, "assignment_type": "dhcp_reservation"},
    {"ip_address": "192.168.30.60", "mac_address": "00:1A:2B:3C:4D:60", "hostname": "cam-front", "vlan_id": 30, "assignment_type": "dhcp_reservation"},
]
