"""
Network Inventory Use Case - Template Definitions

Defines all templates needed for network hardware inventory management.
"""

TEMPLATES = [
    {
        "code": "NET_LOCATION",
        "name": "Physical Location",
        "description": "Physical locations in a hierarchy (building -> floor -> room -> rack)",
        "identity_fields": ["location_code"],
        "fields": [
            {"name": "location_code", "type": "string", "required": True, "description": "Unique location identifier"},
            {"name": "location_type", "type": "term", "terminology_ref": "LOCATION_TYPE", "required": True},
            {"name": "name", "type": "string", "required": True, "description": "Human-readable name"},
            {"name": "parent_location", "type": "string", "description": "Parent location code for hierarchy"},
            {"name": "address", "type": "string", "description": "Physical address (for buildings)"},
            {"name": "floor_number", "type": "integer", "description": "Floor number within building"},
            {"name": "notes", "type": "string"},
        ]
    },
    {
        "code": "NET_DEVICE",
        "name": "Network Device",
        "description": "Base template for all network devices",
        "identity_fields": ["mac_address"],
        "fields": [
            {"name": "hostname", "type": "string", "required": True, "description": "Device hostname"},
            {"name": "mac_address", "type": "string", "required": True, "description": "Primary MAC address"},
            {"name": "device_type", "type": "term", "terminology_ref": "DEVICE_TYPE", "required": True},
            {"name": "manufacturer", "type": "term", "terminology_ref": "MANUFACTURER", "required": True},
            {"name": "model", "type": "string", "required": True},
            {"name": "serial_number", "type": "string"},
            {"name": "firmware_version", "type": "string"},
            {"name": "management_ip", "type": "string", "description": "Management IP address"},
            {"name": "location_code", "type": "string", "description": "Reference to NET_LOCATION"},
            {"name": "rack_unit", "type": "integer", "description": "Starting rack unit position (1 = bottom)"},
            {"name": "rack_height", "type": "integer", "description": "Height in rack units"},
            {"name": "status", "type": "term", "terminology_ref": "DEVICE_STATUS", "required": True},
            {"name": "purchase_date", "type": "date"},
            {"name": "warranty_expiry", "type": "date"},
            {"name": "purchase_price", "type": "number"},
            {"name": "power_watts", "type": "number", "description": "Power consumption in watts"},
            {"name": "notes", "type": "string"},
        ]
    },
    {
        "code": "NET_SWITCH",
        "name": "Network Switch",
        "description": "Extended device info for network switches",
        "extends": "NET_DEVICE",
        "identity_fields": ["mac_address"],
        "fields": [
            {"name": "is_managed", "type": "boolean", "required": True},
            {"name": "layer", "type": "integer", "description": "Layer 2 or Layer 3"},
            {"name": "total_ports", "type": "integer", "required": True},
            {"name": "poe_budget_watts", "type": "number", "description": "Total PoE power budget"},
            {"name": "poe_consumed_watts", "type": "number", "description": "Current PoE consumption"},
            {"name": "supports_stacking", "type": "boolean"},
            {"name": "stack_id", "type": "string", "description": "Stack identifier if stacked"},
            {"name": "stack_role", "type": "string", "description": "master, member, standby"},
            {"name": "management_vlan", "type": "integer"},
            {"name": "spanning_tree_mode", "type": "string", "description": "STP, RSTP, MSTP, PVST"},
        ]
    },
    {
        "code": "NET_SWITCH_PORT",
        "name": "Switch Port",
        "description": "Individual port on a network switch",
        "identity_fields": ["switch_mac", "port_id"],
        "fields": [
            {"name": "switch_mac", "type": "string", "required": True, "description": "MAC of parent switch"},
            {"name": "port_id", "type": "string", "required": True, "description": "Port identifier (e.g., Gi1/0/24)"},
            {"name": "port_label", "type": "string", "description": "Physical label on port"},
            {"name": "speed_capability", "type": "term", "terminology_ref": "PORT_SPEED", "required": True},
            {"name": "current_speed", "type": "term", "terminology_ref": "PORT_SPEED"},
            {"name": "poe_capability", "type": "term", "terminology_ref": "POE_TYPE", "required": True},
            {"name": "poe_allocated_watts", "type": "number"},
            {"name": "poe_drawn_watts", "type": "number"},
            {"name": "sfp_type", "type": "term", "terminology_ref": "SFP_TYPE"},
            {"name": "admin_status", "type": "term", "terminology_ref": "PORT_STATUS", "required": True},
            {"name": "link_status", "type": "term", "terminology_ref": "PORT_STATUS"},
            {"name": "vlan_mode", "type": "string", "description": "access or trunk"},
            {"name": "access_vlan", "type": "integer", "description": "VLAN ID for access ports"},
            {"name": "trunk_vlans", "type": "string", "description": "Allowed VLANs (e.g., 1,10,20 or 1-100)"},
            {"name": "native_vlan", "type": "integer", "description": "Native VLAN for trunk ports"},
            {"name": "connected_mac", "type": "string", "description": "MAC of connected device"},
            {"name": "connected_hostname", "type": "string", "description": "Hostname of connected device"},
            {"name": "description", "type": "string", "description": "Port description/purpose"},
        ]
    },
    {
        "code": "NET_PATCH_PANEL",
        "name": "Patch Panel",
        "description": "Patch panel for cable management",
        "identity_fields": ["panel_id"],
        "fields": [
            {"name": "panel_id", "type": "string", "required": True, "description": "Unique panel identifier"},
            {"name": "name", "type": "string", "required": True},
            {"name": "location_code", "type": "string", "required": True},
            {"name": "rack_unit", "type": "integer"},
            {"name": "rack_height", "type": "integer", "default": 1},
            {"name": "total_ports", "type": "integer", "required": True},
            {"name": "port_type", "type": "term", "terminology_ref": "CABLE_TYPE"},
            {"name": "notes", "type": "string"},
        ]
    },
    {
        "code": "NET_PATCH_PORT",
        "name": "Patch Panel Port",
        "description": "Individual port on a patch panel",
        "identity_fields": ["panel_id", "port_number"],
        "fields": [
            {"name": "panel_id", "type": "string", "required": True},
            {"name": "port_number", "type": "integer", "required": True},
            {"name": "port_label", "type": "string", "description": "Physical label"},
            {"name": "front_type", "type": "string", "description": "device, wallplate, other"},
            {"name": "front_reference", "type": "string", "description": "Device MAC or location"},
            {"name": "back_type", "type": "string", "description": "switch_port, patch_port, other"},
            {"name": "back_switch_mac", "type": "string"},
            {"name": "back_port_id", "type": "string"},
            {"name": "cable_type", "type": "term", "terminology_ref": "CABLE_TYPE"},
            {"name": "tested_date", "type": "date"},
            {"name": "test_result", "type": "string", "description": "pass, fail, not_tested"},
        ]
    },
    {
        "code": "NET_CABLE",
        "name": "Cable Run",
        "description": "Physical cable between two endpoints",
        "identity_fields": ["cable_id"],
        "fields": [
            {"name": "cable_id", "type": "string", "required": True, "description": "Unique cable label"},
            {"name": "cable_type", "type": "term", "terminology_ref": "CABLE_TYPE", "required": True},
            {"name": "cable_color", "type": "term", "terminology_ref": "CABLE_COLOR"},
            {"name": "length_meters", "type": "number"},
            {"name": "endpoint_a_type", "type": "string", "required": True, "description": "switch_port, patch_port, device, wallplate"},
            {"name": "endpoint_a_device_mac", "type": "string"},
            {"name": "endpoint_a_port_id", "type": "string"},
            {"name": "endpoint_a_panel_id", "type": "string"},
            {"name": "endpoint_a_port_number", "type": "integer"},
            {"name": "endpoint_a_location", "type": "string", "description": "Location code for wallplates"},
            {"name": "endpoint_b_type", "type": "string", "required": True},
            {"name": "endpoint_b_device_mac", "type": "string"},
            {"name": "endpoint_b_port_id", "type": "string"},
            {"name": "endpoint_b_panel_id", "type": "string"},
            {"name": "endpoint_b_port_number", "type": "integer"},
            {"name": "endpoint_b_location", "type": "string"},
            {"name": "install_date", "type": "date"},
            {"name": "installed_by", "type": "string"},
            {"name": "tested_date", "type": "date"},
            {"name": "test_result", "type": "string"},
            {"name": "notes", "type": "string"},
        ]
    },
    {
        "code": "NET_VLAN",
        "name": "VLAN",
        "description": "Virtual LAN definition",
        "identity_fields": ["vlan_id"],
        "fields": [
            {"name": "vlan_id", "type": "integer", "required": True},
            {"name": "name", "type": "string", "required": True},
            {"name": "purpose", "type": "term", "terminology_ref": "VLAN_PURPOSE"},
            {"name": "subnet", "type": "string", "description": "CIDR notation"},
            {"name": "gateway", "type": "string"},
            {"name": "dhcp_enabled", "type": "boolean"},
            {"name": "dhcp_start", "type": "string"},
            {"name": "dhcp_end", "type": "string"},
            {"name": "dns_servers", "type": "string", "description": "Comma-separated DNS servers"},
            {"name": "description", "type": "string"},
        ]
    },
    {
        "code": "NET_IP_ASSIGNMENT",
        "name": "IP Assignment",
        "description": "IP address assignments",
        "identity_fields": ["ip_address"],
        "fields": [
            {"name": "ip_address", "type": "string", "required": True},
            {"name": "mac_address", "type": "string", "description": "Associated MAC for reservation"},
            {"name": "hostname", "type": "string"},
            {"name": "vlan_id", "type": "integer"},
            {"name": "assignment_type", "type": "string", "description": "static, dhcp_reservation, dhcp_dynamic"},
            {"name": "dns_name", "type": "string", "description": "FQDN if in DNS"},
            {"name": "last_seen", "type": "datetime"},
            {"name": "notes", "type": "string"},
        ]
    },
]
