"""
Study Plan Use Case - Demo Data (DEMO-001)

Sample clinical study plan for a Phase 2 randomized, double-blind trial.
"""

# =============================================================================
# STUDY DEFINITION
# =============================================================================

STUDY_DEFINITION = {
    "study_id": "DEMO-001",
    "name": "A Phase 2, Randomized, Double-Blind, Placebo-Controlled Study of WIP-101 in Subjects with Moderate Disease",
    "short_name": "WIP-101 Phase 2",
    "description": "This study evaluates the efficacy and safety of WIP-101 100mg daily compared to placebo in subjects with moderate disease over 12 weeks.",
    "phase": "Phase 2",
    "sponsor": "WIP Pharmaceuticals",
    "therapeutic_area": "Immunology",
    "indication": "Moderate autoimmune disease",
    "study_type": "Interventional",
    "blinding": "Double-blind",
    "randomized": True,
    "target_enrollment": 150,
    "duration_weeks": 12,
    "arms_terminology": "STUDY_DEMO001_ARMS",
    "timepoints_terminology": "STUDY_DEMO001_TIMEPOINTS",
    "protocol_version": "1.0",
    "protocol_date": "2024-01-15",
}

# =============================================================================
# STUDY ARMS
# =============================================================================

STUDY_ARMS = [
    {
        "study_id": "DEMO-001",
        "arm_code": "PLACEBO",
        "name": "Placebo",
        "description": "Matching placebo administered once daily",
        "randomization_ratio": 1,
        "is_control": True,
        "treatment_description": "Placebo capsule identical in appearance to active treatment",
        "dose": "Placebo daily",
    },
    {
        "study_id": "DEMO-001",
        "arm_code": "TREATMENT",
        "name": "WIP-101 100mg",
        "description": "WIP-101 100mg administered once daily",
        "randomization_ratio": 2,
        "is_control": False,
        "treatment_description": "WIP-101 capsule containing 100mg active ingredient",
        "dose": "100mg daily",
    },
]

# =============================================================================
# STUDY TIMEPOINTS
# =============================================================================

STUDY_TIMEPOINTS = [
    {
        "study_id": "DEMO-001",
        "timepoint": "SCREENING",
        "name": "Screening",
        "days_from_baseline": -14,
        "hours_from_baseline": 0,
        "window_days_before": 3,
        "window_days_after": 3,
        "phase": "screening",
        "applicable_arms": "ALL",
        "is_required": True,
        "is_anchor": False,
        "description": "Screening visit for eligibility assessment. May occur up to 21 days before baseline.",
    },
    {
        "study_id": "DEMO-001",
        "timepoint": "BASELINE",
        "name": "Baseline (Day 0)",
        "days_from_baseline": 0,
        "hours_from_baseline": 0,
        "window_days_before": 0,
        "window_days_after": 0,
        "phase": "baseline",
        "applicable_arms": "ALL",
        "is_required": True,
        "is_anchor": True,
        "description": "Baseline visit. Day 0. Randomization and first dose.",
    },
    {
        "study_id": "DEMO-001",
        "timepoint": "WEEK_2",
        "name": "Week 2",
        "days_from_baseline": 14,
        "hours_from_baseline": 0,
        "window_days_before": 2,
        "window_days_after": 2,
        "phase": "treatment",
        "applicable_arms": "ALL",
        "is_required": True,
        "is_anchor": False,
        "description": "Week 2 safety phone call. No site visit required.",
    },
    {
        "study_id": "DEMO-001",
        "timepoint": "WEEK_4",
        "name": "Week 4",
        "days_from_baseline": 28,
        "hours_from_baseline": 0,
        "window_days_before": 3,
        "window_days_after": 3,
        "phase": "treatment",
        "applicable_arms": "ALL",
        "is_required": True,
        "is_anchor": False,
        "description": "Week 4 visit. Safety assessments and labs.",
    },
    {
        "study_id": "DEMO-001",
        "timepoint": "WEEK_8",
        "name": "Week 8",
        "days_from_baseline": 56,
        "hours_from_baseline": 0,
        "window_days_before": 3,
        "window_days_after": 3,
        "phase": "treatment",
        "applicable_arms": "ALL",
        "is_required": True,
        "is_anchor": False,
        "description": "Week 8 visit. Interim efficacy and safety assessments.",
    },
    {
        "study_id": "DEMO-001",
        "timepoint": "END_OF_STUDY",
        "name": "End of Study (Week 12)",
        "days_from_baseline": 84,
        "hours_from_baseline": 0,
        "window_days_before": 7,
        "window_days_after": 7,
        "phase": "follow_up",
        "applicable_arms": "ALL",
        "is_required": True,
        "is_anchor": False,
        "description": "End of study visit. Final efficacy and safety assessments.",
    },
    {
        "study_id": "DEMO-001",
        "timepoint": "EARLY_TERM",
        "name": "Early Termination",
        "days_from_baseline": None,
        "hours_from_baseline": None,
        "window_days_before": 0,
        "window_days_after": 7,
        "phase": "early_termination",
        "applicable_arms": "ALL",
        "is_required": False,
        "is_anchor": False,
        "description": "Early termination visit for subjects discontinuing early. Should occur within 7 days of last dose.",
    },
]

# =============================================================================
# PLANNED EVENTS
# =============================================================================

# Events are organized by timepoint for clarity

PLANNED_EVENTS = [
    # -------------------------------------------------------------------------
    # SCREENING EVENTS
    # -------------------------------------------------------------------------
    {
        "template_code": "STUDY_PLANNED_VISIT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "SCREENING",
            "event_type": "visit",
            "applicable_arms": "ALL",
            "description": "Screening visit at study site",
            "is_required": True,
            "sequence_order": 1,
            "location_type": "clinic",
            "estimated_duration_minutes": 120,
            "fasting_required": True,
            "overnight_stay": False,
            "special_instructions": "Subjects must fast for at least 8 hours before the visit.",
        },
    },
    {
        "template_code": "STUDY_PLANNED_EVENT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "SCREENING",
            "event_type": "informed_consent",
            "applicable_arms": "ALL",
            "description": "Obtain informed consent",
            "is_required": True,
            "sequence_order": 2,
        },
    },
    {
        "template_code": "STUDY_PLANNED_EVENT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "SCREENING",
            "event_type": "physical_exam",
            "applicable_arms": "ALL",
            "description": "Complete physical examination",
            "is_required": True,
            "sequence_order": 3,
        },
    },
    {
        "template_code": "STUDY_PLANNED_EVENT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "SCREENING",
            "event_type": "vital_signs",
            "applicable_arms": "ALL",
            "description": "Vital signs (BP, HR, temp, weight)",
            "is_required": True,
            "sequence_order": 4,
        },
    },
    {
        "template_code": "STUDY_PLANNED_LAB",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "SCREENING",
            "event_type": "lab_collection",
            "applicable_arms": "ALL",
            "description": "Screening laboratory tests",
            "is_required": True,
            "sequence_order": 5,
            "sample_types": "serum,plasma,urine",
            "tube_types": "SST, EDTA, urine cup",
            "total_volume_ml": 25.0,
            "fasting_required": True,
            "fasting_hours": 8,
            "processing_instructions": "Process within 2 hours. Ship frozen.",
        },
    },
    {
        "template_code": "STUDY_PLANNED_QUESTIONNAIRE",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "SCREENING",
            "event_type": "questionnaire",
            "applicable_arms": "ALL",
            "description": "Medical history questionnaire",
            "is_required": True,
            "sequence_order": 6,
            "form_name": "Medical History Form",
            "form_version": "1.0",
            "estimated_minutes": 30,
            "administration_method": "interview",
            "recall_period": "lifetime",
        },
    },
    # -------------------------------------------------------------------------
    # BASELINE EVENTS
    # -------------------------------------------------------------------------
    {
        "template_code": "STUDY_PLANNED_VISIT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "BASELINE",
            "event_type": "visit",
            "applicable_arms": "ALL",
            "description": "Baseline visit - Day 0",
            "is_required": True,
            "sequence_order": 1,
            "location_type": "clinic",
            "estimated_duration_minutes": 180,
            "fasting_required": True,
            "overnight_stay": False,
            "special_instructions": "Fast 8 hours. Randomization will occur at this visit.",
        },
    },
    {
        "template_code": "STUDY_PLANNED_EVENT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "BASELINE",
            "event_type": "physical_exam",
            "applicable_arms": "ALL",
            "description": "Abbreviated physical examination",
            "is_required": True,
            "sequence_order": 2,
        },
    },
    {
        "template_code": "STUDY_PLANNED_EVENT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "BASELINE",
            "event_type": "vital_signs",
            "applicable_arms": "ALL",
            "description": "Vital signs",
            "is_required": True,
            "sequence_order": 3,
        },
    },
    {
        "template_code": "STUDY_PLANNED_LAB",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "BASELINE",
            "event_type": "lab_collection",
            "applicable_arms": "ALL",
            "description": "Baseline laboratory tests",
            "is_required": True,
            "sequence_order": 4,
            "sample_types": "serum,plasma",
            "tube_types": "SST, EDTA",
            "total_volume_ml": 20.0,
            "fasting_required": True,
            "fasting_hours": 8,
            "processing_instructions": "Process within 2 hours. Ship frozen.",
        },
    },
    {
        "template_code": "STUDY_PLANNED_QUESTIONNAIRE",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "BASELINE",
            "event_type": "questionnaire",
            "applicable_arms": "ALL",
            "description": "Patient Quality of Life questionnaire",
            "is_required": True,
            "sequence_order": 5,
            "form_name": "SF-36 Quality of Life",
            "form_version": "2.0",
            "estimated_minutes": 15,
            "administration_method": "electronic",
            "recall_period": "past 4 weeks",
        },
    },
    {
        "template_code": "STUDY_PLANNED_IMAGING",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "BASELINE",
            "event_type": "imaging",
            "applicable_arms": "ALL",
            "description": "Baseline MRI",
            "is_required": True,
            "sequence_order": 6,
            "imaging_type": "mri",
            "body_region": "affected joints",
            "contrast_required": True,
            "estimated_duration_minutes": 45,
            "preparation_instructions": "No metal. Remove jewelry. Inform staff of any implants.",
        },
    },
    {
        "template_code": "STUDY_PLANNED_EVENT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "BASELINE",
            "event_type": "drug_admin",
            "applicable_arms": "ALL",
            "description": "First dose of study drug (after randomization)",
            "is_required": True,
            "sequence_order": 7,
        },
    },
    # -------------------------------------------------------------------------
    # WEEK 2 EVENTS (Phone Call Only)
    # -------------------------------------------------------------------------
    {
        "template_code": "STUDY_PLANNED_PHONE_CALL",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "WEEK_2",
            "event_type": "phone_call",
            "applicable_arms": "ALL",
            "description": "Week 2 safety phone call",
            "is_required": True,
            "sequence_order": 1,
            "call_purpose": "Safety assessment and medication compliance check",
            "estimated_duration_minutes": 15,
            "topics_to_cover": "Adverse events, concomitant medications, study drug compliance, general well-being",
        },
    },
    {
        "template_code": "STUDY_PLANNED_EVENT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "WEEK_2",
            "event_type": "adverse_event_check",
            "applicable_arms": "ALL",
            "description": "Adverse event assessment (via phone)",
            "is_required": True,
            "sequence_order": 2,
        },
    },
    # -------------------------------------------------------------------------
    # WEEK 4 EVENTS
    # -------------------------------------------------------------------------
    {
        "template_code": "STUDY_PLANNED_VISIT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "WEEK_4",
            "event_type": "visit",
            "applicable_arms": "ALL",
            "description": "Week 4 visit",
            "is_required": True,
            "sequence_order": 1,
            "location_type": "clinic",
            "estimated_duration_minutes": 90,
            "fasting_required": True,
            "overnight_stay": False,
            "special_instructions": "Fast 8 hours. Bring unused study drug for accountability.",
        },
    },
    {
        "template_code": "STUDY_PLANNED_EVENT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "WEEK_4",
            "event_type": "vital_signs",
            "applicable_arms": "ALL",
            "description": "Vital signs",
            "is_required": True,
            "sequence_order": 2,
        },
    },
    {
        "template_code": "STUDY_PLANNED_LAB",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "WEEK_4",
            "event_type": "lab_collection",
            "applicable_arms": "ALL",
            "description": "Week 4 safety labs",
            "is_required": True,
            "sequence_order": 3,
            "sample_types": "serum",
            "tube_types": "SST",
            "total_volume_ml": 10.0,
            "fasting_required": True,
            "fasting_hours": 8,
            "processing_instructions": "Standard processing.",
        },
    },
    {
        "template_code": "STUDY_PLANNED_EVENT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "WEEK_4",
            "event_type": "adverse_event_check",
            "applicable_arms": "ALL",
            "description": "Adverse event assessment",
            "is_required": True,
            "sequence_order": 4,
        },
    },
    # -------------------------------------------------------------------------
    # WEEK 8 EVENTS
    # -------------------------------------------------------------------------
    {
        "template_code": "STUDY_PLANNED_VISIT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "WEEK_8",
            "event_type": "visit",
            "applicable_arms": "ALL",
            "description": "Week 8 visit - interim assessment",
            "is_required": True,
            "sequence_order": 1,
            "location_type": "clinic",
            "estimated_duration_minutes": 150,
            "fasting_required": True,
            "overnight_stay": False,
            "special_instructions": "Fast 8 hours. Bring unused study drug.",
        },
    },
    {
        "template_code": "STUDY_PLANNED_EVENT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "WEEK_8",
            "event_type": "physical_exam",
            "applicable_arms": "ALL",
            "description": "Abbreviated physical examination",
            "is_required": True,
            "sequence_order": 2,
        },
    },
    {
        "template_code": "STUDY_PLANNED_EVENT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "WEEK_8",
            "event_type": "vital_signs",
            "applicable_arms": "ALL",
            "description": "Vital signs",
            "is_required": True,
            "sequence_order": 3,
        },
    },
    {
        "template_code": "STUDY_PLANNED_LAB",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "WEEK_8",
            "event_type": "lab_collection",
            "applicable_arms": "ALL",
            "description": "Week 8 efficacy and safety labs",
            "is_required": True,
            "sequence_order": 4,
            "sample_types": "serum,plasma",
            "tube_types": "SST, EDTA",
            "total_volume_ml": 20.0,
            "fasting_required": True,
            "fasting_hours": 8,
            "processing_instructions": "Process within 2 hours. Ship frozen.",
        },
    },
    {
        "template_code": "STUDY_PLANNED_QUESTIONNAIRE",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "WEEK_8",
            "event_type": "questionnaire",
            "applicable_arms": "ALL",
            "description": "Interim quality of life assessment",
            "is_required": True,
            "sequence_order": 5,
            "form_name": "SF-36 Quality of Life",
            "form_version": "2.0",
            "estimated_minutes": 15,
            "administration_method": "electronic",
            "recall_period": "past 4 weeks",
        },
    },
    {
        "template_code": "STUDY_PLANNED_IMAGING",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "WEEK_8",
            "event_type": "imaging",
            "applicable_arms": "ALL",
            "description": "Interim MRI",
            "is_required": True,
            "sequence_order": 6,
            "imaging_type": "mri",
            "body_region": "affected joints",
            "contrast_required": True,
            "estimated_duration_minutes": 45,
            "preparation_instructions": "No metal. Remove jewelry.",
        },
    },
    {
        "template_code": "STUDY_PLANNED_EVENT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "WEEK_8",
            "event_type": "adverse_event_check",
            "applicable_arms": "ALL",
            "description": "Adverse event assessment",
            "is_required": True,
            "sequence_order": 7,
        },
    },
    # -------------------------------------------------------------------------
    # END OF STUDY EVENTS
    # -------------------------------------------------------------------------
    {
        "template_code": "STUDY_PLANNED_VISIT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "END_OF_STUDY",
            "event_type": "visit",
            "applicable_arms": "ALL",
            "description": "End of study visit - final assessments",
            "is_required": True,
            "sequence_order": 1,
            "location_type": "clinic",
            "estimated_duration_minutes": 180,
            "fasting_required": True,
            "overnight_stay": False,
            "special_instructions": "Fast 8 hours. Return all unused study drug.",
        },
    },
    {
        "template_code": "STUDY_PLANNED_EVENT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "END_OF_STUDY",
            "event_type": "physical_exam",
            "applicable_arms": "ALL",
            "description": "Complete physical examination",
            "is_required": True,
            "sequence_order": 2,
        },
    },
    {
        "template_code": "STUDY_PLANNED_EVENT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "END_OF_STUDY",
            "event_type": "vital_signs",
            "applicable_arms": "ALL",
            "description": "Vital signs",
            "is_required": True,
            "sequence_order": 3,
        },
    },
    {
        "template_code": "STUDY_PLANNED_LAB",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "END_OF_STUDY",
            "event_type": "lab_collection",
            "applicable_arms": "ALL",
            "description": "Final laboratory tests",
            "is_required": True,
            "sequence_order": 4,
            "sample_types": "serum,plasma,urine",
            "tube_types": "SST, EDTA, urine cup",
            "total_volume_ml": 25.0,
            "fasting_required": True,
            "fasting_hours": 8,
            "processing_instructions": "Process within 2 hours. Ship frozen.",
        },
    },
    {
        "template_code": "STUDY_PLANNED_QUESTIONNAIRE",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "END_OF_STUDY",
            "event_type": "questionnaire",
            "applicable_arms": "ALL",
            "description": "Final quality of life assessment",
            "is_required": True,
            "sequence_order": 5,
            "form_name": "SF-36 Quality of Life",
            "form_version": "2.0",
            "estimated_minutes": 15,
            "administration_method": "electronic",
            "recall_period": "past 4 weeks",
        },
    },
    {
        "template_code": "STUDY_PLANNED_IMAGING",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "END_OF_STUDY",
            "event_type": "imaging",
            "applicable_arms": "ALL",
            "description": "Final MRI",
            "is_required": True,
            "sequence_order": 6,
            "imaging_type": "mri",
            "body_region": "affected joints",
            "contrast_required": True,
            "estimated_duration_minutes": 45,
            "preparation_instructions": "No metal. Remove jewelry.",
        },
    },
    {
        "template_code": "STUDY_PLANNED_EVENT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "END_OF_STUDY",
            "event_type": "adverse_event_check",
            "applicable_arms": "ALL",
            "description": "Final adverse event assessment",
            "is_required": True,
            "sequence_order": 7,
        },
    },
    # -------------------------------------------------------------------------
    # EARLY TERMINATION EVENTS
    # -------------------------------------------------------------------------
    {
        "template_code": "STUDY_PLANNED_VISIT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "EARLY_TERM",
            "event_type": "visit",
            "applicable_arms": "ALL",
            "description": "Early termination visit",
            "is_required": True,
            "sequence_order": 1,
            "location_type": "clinic",
            "estimated_duration_minutes": 120,
            "fasting_required": True,
            "overnight_stay": False,
            "special_instructions": "Fast 8 hours. Return all unused study drug. Complete within 7 days of last dose.",
        },
    },
    {
        "template_code": "STUDY_PLANNED_EVENT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "EARLY_TERM",
            "event_type": "physical_exam",
            "applicable_arms": "ALL",
            "description": "Complete physical examination",
            "is_required": True,
            "sequence_order": 2,
        },
    },
    {
        "template_code": "STUDY_PLANNED_EVENT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "EARLY_TERM",
            "event_type": "vital_signs",
            "applicable_arms": "ALL",
            "description": "Vital signs",
            "is_required": True,
            "sequence_order": 3,
        },
    },
    {
        "template_code": "STUDY_PLANNED_LAB",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "EARLY_TERM",
            "event_type": "lab_collection",
            "applicable_arms": "ALL",
            "description": "Early termination laboratory tests",
            "is_required": True,
            "sequence_order": 4,
            "sample_types": "serum,plasma",
            "tube_types": "SST, EDTA",
            "total_volume_ml": 20.0,
            "fasting_required": True,
            "fasting_hours": 8,
            "processing_instructions": "Process within 2 hours. Ship frozen.",
        },
    },
    {
        "template_code": "STUDY_PLANNED_EVENT",
        "data": {
            "study_id": "DEMO-001",
            "timepoint": "EARLY_TERM",
            "event_type": "adverse_event_check",
            "applicable_arms": "ALL",
            "description": "Adverse event assessment and documentation of reason for early termination",
            "is_required": True,
            "sequence_order": 5,
        },
    },
]

# =============================================================================
# COMBINED DATA FOR SEEDING
# =============================================================================

DEMO_DATA = {
    "study_definition": STUDY_DEFINITION,
    "study_arms": STUDY_ARMS,
    "study_timepoints": STUDY_TIMEPOINTS,
    "planned_events": PLANNED_EVENTS,
}
