"""
Document generators for test data.

This module provides a simple interface to generate documents for any template.
The actual generation is handled by the template-driven DocumentGenerator,
which reads template definitions and terminology values to produce valid documents.

Usage:
    from seed_data import generators

    # Generate a single document
    person = generators.generate_document("PERSON", index=0)

    # Generate multiple documents
    for i in range(10):
        employee = generators.generate_document("EMPLOYEE", index=i)

    # Get generator for a specific template
    gen = generators.get_generator("PRODUCT")
    if gen:
        product = gen(0)
"""
from __future__ import annotations

from typing import Any, Callable

from .document_generator import DocumentGenerator, generate_document as _generate


# Singleton generator instance
_generator: DocumentGenerator | None = None


def get_document_generator() -> DocumentGenerator:
    """Get the document generator instance."""
    global _generator
    if _generator is None:
        _generator = DocumentGenerator()
    return _generator


def generate_document(template_value: str, index: int = 0) -> dict[str, Any]:
    """
    Generate a valid document for a template.

    The document is generated by:
    1. Reading the template definition (fields, types, terminology refs)
    2. Generating appropriate values for each field
    3. Applying validation rules to ensure compliance

    Args:
        template_value: Template code (e.g., "PERSON", "EMPLOYEE", "ORDER")
        index: Index for unique ID generation

    Returns:
        A document dict that satisfies all template validation rules
    """
    return get_document_generator().generate(template_value, index)


def get_generator(template_value: str) -> Callable[[int], dict[str, Any]] | None:
    """
    Get a generator function for a template value.

    This provides backwards compatibility with the old generator interface.

    Args:
        template_value: Template value (e.g., "PERSON", "EMPLOYEE")

    Returns:
        A function that takes an index and returns a document, or None if template not found
    """
    generator = get_document_generator()
    template = generator.templates.get_template(template_value)

    if template is None:
        return None

    def gen(index: int = 0) -> dict[str, Any]:
        return generator.generate(template_value, index)

    return gen


# Convenience functions for common templates
def generate_person(index: int = 0) -> dict[str, Any]:
    """Generate a PERSON document."""
    return generate_document("PERSON", index)


def generate_employee(index: int = 0) -> dict[str, Any]:
    """Generate an EMPLOYEE document."""
    return generate_document("EMPLOYEE", index)


def generate_product(index: int = 0) -> dict[str, Any]:
    """Generate a PRODUCT document."""
    return generate_document("PRODUCT", index)


def generate_order(index: int = 0) -> dict[str, Any]:
    """Generate an ORDER document."""
    return generate_document("ORDER", index)


def generate_customer(index: int = 0) -> dict[str, Any]:
    """Generate a CUSTOMER document."""
    return generate_document("CUSTOMER", index)


def generate_invoice(index: int = 0) -> dict[str, Any]:
    """Generate an INVOICE document."""
    return generate_document("INVOICE", index)


# List of all supported template values (for reference)
SUPPORTED_TEMPLATES = [
    # Base templates
    "ADDRESS",
    "CONTACT_INFO",
    "MONEY",
    # Domain templates
    "PERSON",
    "PRODUCT",
    "ORDER_LINE",
    "ORDER",
    "CUSTOMER",
    "INVOICE",
    "MEDICAL_RECORD",
    "ISSUE_TICKET",
    # Inheritance templates
    "EMPLOYEE",
    "CONTRACTOR",
    "MANAGER",
    "INTERN",
    "BILLING_ADDRESS",
    "PHYSICAL_PRODUCT",
    "DIGITAL_PRODUCT",
    # Edge case templates
    "MINIMAL",
    "ALL_TYPES",
    "DEEP_NEST",
    "LARGE_FIELDS",
    "COMPLEX_RULES",
    "ARRAY_HEAVY",
    # Append-only (no identity_fields)
    "EVENT_LOG",
]
