"""Universal synonym resolution for WIP entity IDs.

Resolves human-readable identifiers (e.g., "STATUS", "PATIENT", "STATUS:approved")
to canonical entity IDs via Registry synonym lookup.

Canonical IDs (UUID format) pass through without any Registry call.
Non-canonical IDs are resolved via the Registry's POST /resolve endpoint
with a TTL cache (5 minutes) to minimise latency.

Usage:
    from wip_auth.resolve import resolve_entity_id, resolve_entity_ids

    # Single resolution
    canonical_id = await resolve_entity_id("STATUS", "terminology", "wip")

    # Batch resolution
    id_map = await resolve_entity_ids(["STATUS", "GENDER"], "terminology", "wip")
"""

import logging
import os
import re
import time
from typing import Any

import httpx

logger = logging.getLogger(__name__)

# UUID pattern: 8-4-4-4-12 hex chars (covers UUID4, UUID7, and similar)
_UUID_PATTERN = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$",
    re.IGNORECASE,
)

# TTL cache: {cache_key: (canonical_id, expire_time)}
_resolution_cache: dict[str, tuple[str, float]] = {}
_CACHE_TTL = 300  # 5 minutes


def _get_registry_url() -> str:
    """Get Registry URL from environment."""
    return os.getenv(
        "WIP_AUTH_REGISTRY_URL",
        os.getenv("REGISTRY_URL", "http://localhost:8001"),
    )


def _get_api_key() -> str:
    """Get API key for Registry calls."""
    return os.getenv(
        "REGISTRY_API_KEY",
        os.getenv("API_KEY", "dev_master_key_for_testing"),
    )


def is_canonical_format(raw_id: str) -> bool:
    """Check if an ID is already in canonical format (UUID).

    Canonical IDs are UUIDs (generated by Registry). Non-canonical IDs are
    human-readable values that need synonym resolution.
    """
    return bool(_UUID_PATTERN.match(raw_id))


def _build_composite_key(
    raw_id: str,
    entity_type: str,
    namespace: str,
) -> dict[str, Any]:
    """Build a composite key from a synonym string and context.

    Term references use colon notation: "TERMINOLOGY:TERM_VALUE"
    All other entity types use the plain value.

    Args:
        raw_id: The human-readable identifier
        entity_type: Singular entity type (terminology, term, template, document)
        namespace: Current namespace
    """
    if entity_type == "term" and ":" in raw_id:
        terminology, value = raw_id.split(":", 1)
        return {
            "ns": namespace,
            "type": "term",
            "terminology": terminology,
            "value": value,
        }

    return {
        "ns": namespace,
        "type": entity_type,
        "value": raw_id,
    }


def _get_cached(cache_key: str) -> str | None:
    """Get a cached resolution result if still valid."""
    entry = _resolution_cache.get(cache_key)
    if entry is None:
        return None
    canonical_id, expire_time = entry
    if time.monotonic() > expire_time:
        del _resolution_cache[cache_key]
        return None
    return canonical_id


def _set_cached(cache_key: str, canonical_id: str) -> None:
    """Cache a resolution result."""
    _resolution_cache[cache_key] = (canonical_id, time.monotonic() + _CACHE_TTL)


def clear_resolution_cache() -> None:
    """Clear the resolution cache (useful for testing)."""
    _resolution_cache.clear()


class EntityNotFoundError(Exception):
    """Raised when synonym resolution finds no matching entity."""

    def __init__(self, identifier: str, entity_type: str):
        self.identifier = identifier
        self.entity_type = entity_type
        super().__init__(f"No {entity_type} found for identifier: {identifier}")


async def resolve_entity_id(
    raw_id: str,
    entity_type: str,
    namespace: str,
) -> str:
    """Resolve a synonym or canonical ID to the canonical ID.

    Returns raw_id unchanged if it's already in canonical format (UUID).
    Raises EntityNotFoundError if synonym lookup fails.

    Args:
        raw_id: The identifier (canonical UUID or human-readable synonym)
        entity_type: Singular entity type: terminology, term, template, document
        namespace: Current namespace for resolution context

    Returns:
        The canonical entity ID (UUID)

    Raises:
        EntityNotFoundError: If the synonym is not found in Registry
    """
    if is_canonical_format(raw_id):
        return raw_id

    cache_key = f"{namespace}:{entity_type}:{raw_id}"
    cached = _get_cached(cache_key)
    if cached:
        return cached

    composite_key = _build_composite_key(raw_id, entity_type, namespace)

    registry_url = _get_registry_url()
    api_key = _get_api_key()

    async with httpx.AsyncClient(timeout=10.0) as client:
        response = await client.post(
            f"{registry_url}/api/registry/entries/resolve",
            headers={"X-API-Key": api_key, "Content-Type": "application/json"},
            json=[{"composite_key": composite_key}],
        )

    if response.status_code != 200:
        logger.warning(
            "Registry resolve failed for %s (%s): %s",
            raw_id, entity_type, response.status_code,
        )
        raise EntityNotFoundError(raw_id, entity_type)

    data = response.json()
    results = data.get("results", [])
    if results and results[0].get("status") == "found":
        canonical_id = results[0]["entry_id"]
        _set_cached(cache_key, canonical_id)
        return canonical_id

    raise EntityNotFoundError(raw_id, entity_type)


async def resolve_entity_ids(
    raw_ids: list[str],
    entity_type: str,
    namespace: str,
) -> dict[str, str]:
    """Batch resolve multiple synonyms/canonical IDs.

    Returns a mapping of {raw_id: canonical_id} for all inputs.
    Canonical IDs pass through unchanged. Non-canonical IDs are resolved
    via a single batch call to Registry.

    Args:
        raw_ids: List of identifiers (mix of canonical and synonym)
        entity_type: Singular entity type
        namespace: Current namespace

    Returns:
        Dict mapping each raw_id to its canonical ID

    Raises:
        EntityNotFoundError: If any synonym is not found
    """
    result: dict[str, str] = {}
    to_resolve: list[str] = []

    for raw_id in raw_ids:
        if is_canonical_format(raw_id):
            result[raw_id] = raw_id
            continue

        cache_key = f"{namespace}:{entity_type}:{raw_id}"
        cached = _get_cached(cache_key)
        if cached:
            result[raw_id] = cached
        else:
            to_resolve.append(raw_id)

    if not to_resolve:
        return result

    # Build composite keys for all unresolved IDs
    composite_keys = [
        _build_composite_key(rid, entity_type, namespace)
        for rid in to_resolve
    ]

    registry_url = _get_registry_url()
    api_key = _get_api_key()

    async with httpx.AsyncClient(timeout=10.0) as client:
        response = await client.post(
            f"{registry_url}/api/registry/entries/resolve",
            headers={"X-API-Key": api_key, "Content-Type": "application/json"},
            json=[{"composite_key": ck} for ck in composite_keys],
        )

    if response.status_code != 200:
        logger.warning("Registry batch resolve failed: %s", response.status_code)
        raise EntityNotFoundError(to_resolve[0], entity_type)

    data = response.json()
    for i, resolve_result in enumerate(data.get("results", [])):
        raw_id = to_resolve[i]
        if resolve_result.get("status") == "found":
            canonical_id = resolve_result["entry_id"]
            cache_key = f"{namespace}:{entity_type}:{raw_id}"
            _set_cached(cache_key, canonical_id)
            result[raw_id] = canonical_id
        else:
            raise EntityNotFoundError(raw_id, entity_type)

    return result
